### ISSUE TITLE
Support python3?

### ISSUE THREAD

**Issue by ipeisong** [shakefu/humbledb#6]
Now install with pip3 got error:

Downloading/unpacking humbledb
  Downloading humbledb-5.4.1.tar.gz
  Running setup.py (path:/private/var/folders/tx/l2n8tjgj1c3bmp2bv0jxgsqc0000gn/T/pip_build_peisong/humbledb/setup.py) egg_info for package humbledb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/tx/l2n8tjgj1c3bmp2bv0jxgsqc0000gn/T/pip_build_peisong/humbledb/setup.py", line 7, in <module>
        "})());exec(a+'=g()');"%'humbledb')
      File "<string>", line 1, in <module>
    ImportError: No module named 'compiler'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/tx/l2n8tjgj1c3bmp2bv0jxgsqc0000gn/T/pip_build_peisong/humbledb/setup.py", line 7, in <module>

```
"})());exec(a+'=g()');"%'humbledb')
```

  File "<string>", line 1, in <module>

ImportError: No module named 'compiler'

---

Cleaning up...

**Comment by hongyuan1306** [comment]
humbledb depends quite extensively on pytools. But pytools is not Python3 compatible.

**Comment by shakefu** [comment]
I've updated Pytool to support Python 3.3 and higher as well as add 3.3 and 3.4 builds to Travis-CI. Hopefully someone will want to help contribute to get HumbleDB Python3 compatible.
